### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Oxmel** [Oxmel/hotspot-connect#6]
### Liste des changements prévus

- [ ] Sécurité minimale sur les identifiants (fichier à part + chmod 600)
- [ ] Refactoriser le module de diagnostic
- [ ] Séparer la configuration du logger avec le module logging.config
- [ ] Effectuer tout le travail de vérification, test, retry, etc... sur le module principal
- [ ] Remplacer le timer fixe par du [polling](https://twitter.com/0xm3l/status/1277301855480172544) pour obtenir plus rapidement l'état de l'association avec le hotspot
- [ ] Intégrer la possibilité d'utilser un service VPN pour sécuriser le trafic entre le client et le hotspot
